import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import icone from "@/../public/icone.png"

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["1000", "200", "300", "400", "500", "600", '700', "800", "900"]
})

export const metadata: Metadata = {
  title: "ToDo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="shortcut icon" href="../../public/icone.png" type="image/x-icon" />
      </head>
      <body
        className={mulish.className}
      >
        {children}
      </body>
    </html>
  );
}
